[package]
name = "wait_group"
version = "0.1.0"
authors = ["Nik Bond <nikbond97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rayon = "1.3.0"
